name: Docker Image CD

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the open-webui Docker image
      run: |
        docker build  . --tag ghcr.io/redevltd/open-webui:latest        
        docker push ghcr.io/redevltd/open-webui:latest
